# -*- coding: utf-8 -*-
"""TCC_YahooFinances.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kC4SHJC02VVM7pujI6S3dRP1mHng0dHh
"""

!pip install yfinance
!pip install yahoofinancials

import datetime
import csv
import sys

import pandas as pd
import yfinance as yf
from yahoofinancials import YahooFinancials

from google.colab import files

def get_targets(df):
  target = [1]
  #prev_close = df_stock.loc[0, 'close']
  for i in range(1, len(df.index)):
    prev_close = df.loc[i-1, 'close']
    cur_close = df.loc[i, 'close']

    if cur_close >= prev_close:
      target.append(1)
    else:
      target.append(0)
  return target

# ex.: stock = PETR4.SA; sdate and edate = '2021-01-30'
def get_stock_prices(stock, sdate, edate, interval='daily'):
  yahoo_financials = YahooFinancials(stock)
  data = yahoo_financials.get_historical_price_data(start_date=sdate,
                                                    end_date=edate,
                                                    time_interval=interval)

  ya_df = pd.DataFrame(data[stock]['prices'])
  ya_df = ya_df.drop('date', axis=1)
  ya_df.insert(0, 'formatted_date', ya_df.pop('formatted_date'))
  ya_df.rename(columns={'formatted_date': 'date'}, inplace=True)

  ya_df['target'] = get_targets(ya_df)

  ffname = "stock_"+stock+"_"+sdate+"_"+edate+".csv"

  ya_df.to_csv(ffname, sep=',', index=False)

  files.download(ffname)

  return ya_df

start_d = '2008-01-01'
end_d   = '2022-09-20'

get_stock_prices('PETR4.SA', start_d, end_d)
get_stock_prices('VALE3.SA', start_d, end_d)
get_stock_prices('ABEV3.SA', start_d, end_d)
get_stock_prices('ITUB4.SA', start_d, end_d)
get_stock_prices('BBDC4.SA', start_d, end_d)

df_finance.head()